spring.application.name=h

spring.config.import=optional:file:.env[.properties]


app.upload.comic-dir=upload/comic
app.upload.chapter-dir=upload/chapter

# H2 Database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port
server.port=8080

# JWT Configuration
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-milliseconds=86400000

# SpringDoc OpenAPI configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

