-- V1__init_schema.sql
-- Initial schema creation for Hcomic

-- Create users table
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    role VARCHAR(50) NOT NULL,
    display_name VARCHAR(255),
    avatar VARCHAR(255),
    bio TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- Create comics table
CREATE TABLE comics (
    comic_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE,
    description TEXT,
    author VARCHAR(255),
    user_id BIGINT,
    cover_image VARCHAR(255),
    view_count BIGINT DEFAULT 0,
    like_count BIGINT DEFAULT 0,
    rating DOUBLE PRECISION DEFAULT 0.0,
    status VARCHAR(50),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_comic_uploader FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL
);

-- Create chapters table
CREATE TABLE chapters (
    chapter_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comic_id BIGINT NOT NULL,
    chapter_number DOUBLE PRECISION NOT NULL,
    title VARCHAR(255),
    slug VARCHAR(255) NOT NULL,
    view_count BIGINT DEFAULT 0,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_chapter_comic FOREIGN KEY (comic_id) REFERENCES comics(comic_id) ON DELETE CASCADE,
    CONSTRAINT uk_chapter_comic_number UNIQUE (comic_id, chapter_number),
    CONSTRAINT uk_chapter_comic_slug UNIQUE (comic_id, slug)
);

CREATE INDEX idx_chapter_comic_number ON chapters(comic_id, chapter_number);
CREATE INDEX idx_chapter_comic_slug ON chapters(comic_id, slug);

-- Create chapter_images table
CREATE TABLE chapter_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chapter_id BIGINT NOT NULL,
    image_path VARCHAR(255) NOT NULL,
    page_number INT NOT NULL,
    CONSTRAINT fk_chapter_image_chapter FOREIGN KEY (chapter_id) REFERENCES chapters(chapter_id) ON DELETE CASCADE
);

-- Create comic_likes table
CREATE TABLE comic_likes (
    like_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    comic_id BIGINT NOT NULL,
    CONSTRAINT fk_comic_like_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_comic_like_comic FOREIGN KEY (comic_id) REFERENCES comics(comic_id) ON DELETE CASCADE,
    CONSTRAINT uk_comic_like_user_comic UNIQUE (user_id, comic_id)
);

-- Create comic_rates table
CREATE TABLE comic_rates (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    comic_id BIGINT NOT NULL,
    rating DOUBLE PRECISION,
    CONSTRAINT fk_comic_rate_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_comic_rate_comic FOREIGN KEY (comic_id) REFERENCES comics(comic_id) ON DELETE CASCADE,
    CONSTRAINT uk_comic_rate_user_comic UNIQUE (user_id, comic_id)
);

-- Create comments table
CREATE TABLE comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    user_id BIGINT NOT NULL,
    comic_id BIGINT NOT NULL,
    chapter_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_comic FOREIGN KEY (comic_id) REFERENCES comics(comic_id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_chapter FOREIGN KEY (chapter_id) REFERENCES chapters(chapter_id) ON DELETE SET NULL
);

CREATE INDEX idx_comment_comic_id ON comments(comic_id);
CREATE INDEX idx_comment_chapter_id ON comments(chapter_id);
CREATE INDEX idx_comment_created_at ON comments(created_at);
CREATE INDEX idx_comment_comic_chapter ON comments(comic_id, chapter_id);
CREATE INDEX idx_comment_comic_created ON comments(comic_id, created_at);
CREATE INDEX idx_comment_chapter_created ON comments(chapter_id, created_at);
