-- V3__add_reading_history_library_and_bookmarks.sql
-- Create reading_histories table
CREATE TABLE reading_histories (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    comic_id BIGINT NOT NULL,
    chapter_id BIGINT NOT NULL,
    page_number INT DEFAULT 1,
    percentage DOUBLE PRECISION DEFAULT 0.0,
    updated_at TIMESTAMP,
    CONSTRAINT fk_history_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_history_comic FOREIGN KEY (comic_id) REFERENCES comics(comic_id) ON DELETE CASCADE,
    CONSTRAINT fk_history_chapter FOREIGN KEY (chapter_id) REFERENCES chapters(chapter_id) ON DELETE CASCADE,
    CONSTRAINT uk_history_user_comic UNIQUE (user_id, comic_id)
);

CREATE INDEX idx_history_user_updated ON reading_histories(user_id, updated_at);

-- Create user_comic_libraries table
CREATE TABLE user_comic_libraries (
    library_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    comic_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_library_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_library_comic FOREIGN KEY (comic_id) REFERENCES comics(comic_id) ON DELETE CASCADE,
    CONSTRAINT uk_library_user_comic UNIQUE (user_id, comic_id)
);

CREATE INDEX idx_library_user_status ON user_comic_libraries(user_id, status);

-- Create page_bookmarks table
CREATE TABLE page_bookmarks (
    bookmark_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    comic_id BIGINT NOT NULL,
    chapter_id BIGINT NOT NULL,
    page_number INT NOT NULL,
    note VARCHAR(500),
    created_at TIMESTAMP,
    CONSTRAINT fk_bookmark_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_bookmark_comic FOREIGN KEY (comic_id) REFERENCES comics(comic_id) ON DELETE CASCADE,
    CONSTRAINT fk_bookmark_chapter FOREIGN KEY (chapter_id) REFERENCES chapters(chapter_id) ON DELETE CASCADE,
    CONSTRAINT uk_bookmark_user_chapter_page UNIQUE (user_id, chapter_id, page_number)
);

CREATE INDEX idx_bookmark_user_comic ON page_bookmarks(user_id, comic_id);
